#!/bin/sh

RRLOG="/tmp/rrlog"

if [ -n "$RRLOG" ]; then
  echo `awk '{print $1}' /proc/uptime` $REMOTE_ADDR:$REMOTE_PORT \'$HTTP_REFERER\' \'$HTTP_USER_AGENT\' >>"$RRLOG"
fi

# To signal a rickroll, blink for 15 seconds
(echo timer > /sys/devices/platform/leds-gpio/leds/tp-link:blue:system/trigger ;sleep 15;echo none > /sys/devices/platform/leds-gpio/leds/tp-link:blue:system/trigger) &


echo "Content-type: image/gif"
echo ""
cat /www/1x1.gif
