#!/bin/sh
make image PROFILE=TLWR703 PACKAGES="tinc kmod-ipv6 -dnsmasq -radvd ip wireless-tools block-mount kmod-usb-core kmod-usb2 kmod-usb-storage -kmod-ppp -kmod-pppoe -kmod-pppox -ppp -ppp-mod-pppoe" FILES=customfiles/
