#! /bin/sh
#
# //node/tools/latest-version - retrieve the latest node version from the IN
#
set -euf

# cd //node
cd $(readlink -f $(dirname $0)/..)

# PATH prepend //util/bin
export PATH="$PWD/../util/bin${PATH+:$PATH}"

# TODO punani install executable: curl

curl -fsS http://nodejs.org/ |
    hrefs |
    sed -n 's:.*node-v\([0-9.]\+\)\.tar\.gz:\1:p' |
    sort |
    tail -n 1
