#! /bin/sh
case "$1" in
  (--help)
    echo "play an audio file" ;;
  (*)
    exec 2>&1
    ffs='wav mp3 ogg asf flac'
    
    if test -z "$*" ; then
      ls $HOME/noise/samples | sed -r '
          s:\.('"`echo "$ffs" | tr \  \|`"')$: [30m\1[m:
          s:^:/play :
          s:.*:[32m&[m:
      '
    else
      for i in $ffs ; do
        f=$HOME/noise/samples/$1.$i
        test -f "$f" &&
            case "$i" in
              wav) aplay "$f" & ;;
                *) mplayer "$f" & ;;
            esac && break 
      done || cat<<EOF
[33m\
Keine Audiodatei mit dem Namen [4m$1[;33m.EXT gefunden... \
am besten gleich uploaden:
$ scp NAME $LOGNAME@shack:noise/samples/

folgende Dateiendungen werden erkannt: $ffs[m
EOF
    fi
esac
