#! /bin/sh

case "$1" in
  (--help) echo do some test-module related stuff ;;
  (*)
    
    echo -n ">> "    
    read TEST
    if [ $TEST == 'q' ]; then exit; fi
    echo /wall [33m@@[m $TEST >$NOISE_linefeed
    #sleep 1
    #sleep 1; echo /test >$NOISE_linefeed &
esac
