#! /bin/sh

case "$1" in
  (--help)
    echo "say current time" ;;
  (*)
    exec >>$NOISE_linefeed
    k=`date +%k`
    M=`date +%M|sed 's/0*//'`
    echo /set pitch 10
    case "$lang" in
      (de|'') echo "/espeak Es ist $k Uhr $M" ;;
      (en|*-en)
          test -z "$M" || M="and $M minutes"
          echo "/espeak It is $k o clock $M" ;;
      (*) echo "[31mError: unsupported [4mlang[0;31m = $lang[m" >&2
    esac
    echo /set pitch ${noise_pitch-100}
esac 2>&1
