#! /bin/sh
qname="`readlink -f "$0"`"
dirname="`dirname "$qname"`"
if test -d "$dirname/modules" ; then
  export NOISE_PATH="${NOISE_PATH+$NOISE_PATH:}$dirname/modules"
fi
exec tcpserver -c 423 -t 2 -D 0.0.0.0 42380 "$dirname/noise"
