#!/bin/sh
#ESSID MAC CHANNEL ENCRYPTION WPA WPA2
cat /etc/autowifi/wifi_keys | while IFS='|' read SSID MAC KEY; do
    if [ "$1" == "$SSID" -a "$2" == "$MAC" ]; then
        echo $KEY
        exit 0
    fi
done
exit 1
