#!/bin/sh
#set -x
HERE=$(dirname $(readlink -f $0))
. $HERE/../../../profile
MACHINE=chinaman
ln -s $HERE/index $HERE/../../active/${MACHINE}_ati_temper
mkdir -p $PDIR
cat > $PDIR/$MACHINE.conf <<EOF 
set terminal png transparent nocrop enhanced font arial 8 size 500
set xdata time
set autoscale
set grid
set title "$MACHINE Temperature"
set timefmt "%Y-%m-%dT%H:%M:%S"
set format x "%d"
set xlabel "Day"
plot "$ADIR/${MACHINE}_ati_temper" using 1:2 smooth bezier title "gpu0" with lines , \
"$ADIR/${MACHINE}_ati_temper" using 1:3 smooth bezier title "gpu1" with lines , \
"$ADIR/${MACHINE}_ati_temper" using 1:4 smooth bezier title "cpu0" with lines , \
"$ADIR/${MACHINE}_ati_temper" using 1:5 smooth bezier title "rack" with lines
EOF

sed -e 's/set xlabel.*/set xlabel "Time of Day"/' \
    -e 's/set format.*/set format x "%H"/' \
    -e "s/set title.*/set title \"${MACHINE} 24 hours Temperature\"/" \
    -e "s/${MACHINE}_ati_temper/${MACHINE}_last_day/g" \
    $PDIR/${MACHINE}.conf >$PDIR/${MACHINE}_last_day.conf

