#!/bin/sh
#set -x
HERE=$(dirname $(readlink -f $0))
. $HERE/../../../profile
mkdir -p $PDIR
cat > $PDIR/chinaman.conf <<EOF 
set terminal png transparent nocrop enhanced font arial 8 size 500
set xdata time
set autoscale
set grid
set title "Chinaman Temperature"
set timefmt "%Y-%m-%dT%H:%M:%S"
set format x "%d"
set xlabel "Day"
plot "$ADIR/chinaman_ati_temper" using 1:2 smooth bezier title "gpu0" with lines , \
"$ADIR/chinaman_ati_temper" using 1:3 smooth bezier title "gpu1" with lines , \
"$ADIR/chinaman_ati_temper" using 1:4 smooth bezier title "cpu0" with lines , \
"$ADIR/chinaman_ati_temper" using 1:5 smooth bezier title "rack" with lines
EOF

sed -e 's/set xlabel.*/set xlabel "Time of Day"/' \
    -e 's/set format.*/set format x "%H"/' \
    -e 's/set title.*/set title "Chinaman 24 hours Temperature"/' \
    -e "s/chinaman_ati_temper/chinaman_last_day/g" \
    $PDIR/chinaman.conf >$PDIR/chinaman_last_day.conf
