#! /bin/sh

h="/lib/modules/$(uname -r)/build/include/linux/syscalls.h"
sed -n 's/.*sys_\([^)]\+\)(.*/\1/p' $h | while read f; do
  x="`( man 3p $f || man 3 $f || man $f ) 2>/dev/null`"
  echo "`
    echo "$x" | grep -q ENAMETOOLONG && echo 1 || echo 0``
    echo "$x" | grep -q EACCES && echo 1 || echo 0``
  ` $f"
done
