#!/bin/sh
cd $(dirname $0)
U="${1:-$USER}"
H="$(grep "^$U" /etc/passwd | cut -d : -f 6)"
echo "deploying for user $U to $H/.ssh"
read
mkdir -p $H/.ssh
chown $U $H
chown $U $H/.ssh
cp -r skel/home/.ssh/authorized_keys $H/.ssh
