#! /bin/sh
set -x
cat>/etc/motd.tail<<EOF
KREBS PAINLOAD (MORE COBRA)
[31;1m  x x              x x
 xx xx  xx    xx  xx xx
 xx xx  xx    xx  xx xx
  xxx    x     x   xxx
   x  xxxxxxxxxxxx  x
    xxxxxxxxxxxxxxxx
   x  xxxxxxxxxxxx  x
  x  x   x     x  x  x
  x  x   x     x  x  x[m
EOF

for i in etc/*; do
  cat $i > /$i
done

set +x
