#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

TINCNAME='retiolum'
case "$1" in
  start)
    stat_busy "Starting retiolum Daemon"
    success=0
    /home/death/git/retiolum/.scripts/tinc_multicast/retiolum.py -n retiolum -T &
    sleep 2
    if [ $success -eq 0 ]; then
      add_daemon retiolum
      stat_done
    else
      stat_fail
    fi
    ;;
  stop)
    stat_busy "Stopping retiolum Daemon"
    kill `cat /var/lock/retiolum.retiolum`
    rm_daemon retiolum
    stat_done
    ;;
  restart)
    $0 stop
    sleep 4
    $0 start
    ;;
  *)
    echo "usage $0 {start¦stop¦restart}"
esac
exit 0
