#!/usr/bin/python
import json,urllib,datetime,sys
today = datetime.datetime.now()

result = json.load(sys.stdin)
print today.strftime("%Y-%m-%dT%H:%M:%S"),
print '%s' % result["blocks"],
print '%s' % result["difficulty"],
print '%s' % result["keypoololdest"],
#print '%s' % result["keypoolsize"]
