#! /bin/sh
set -euf

# cd //
cd $(dirname $(readlink -f $0))/../..

max=70
step=10
min=0

# fade-out streams
for i in `seq $max -$step $min`; do
  amixer -q -c 0 -D hw:0 sset Front $i%
  sleep 0.1
done
streams/streams stop

amixer -q -c 0 -D hw:0 sset Front $max%
mplayer god/overlord/announce.mp3 >/dev/null
espeak -v de -s 120 -a 900 "$*"

# fade-in streams
streams/streams start
for i in `seq $min $step $max`; do
  sleep 0.1
  amixer -q -c 0 -D hw:0 sset Front $i%
done
