#!/bin/sh
#@info
#@strict
#@include core
exists dircolors || die "no dircolors in PATH, bailing out"

info "fixing dircolors for $(id -un)"
dircolors -p > $HOME/.dircolors
sed -i 's/\(DIR \).*/\101;36/' $HOME/.dircolors
! grep -q 'dircolors' $HOME/.profile && \
	info "adding dircolors line to $HOME/.profile" && \
	echo 'eval `dircolors -b $HOME/.dircolors`' >> $HOME/.profile
info "done"
