#!/bin/sh
#@include core
#@include network
#@include punani
#@include tor



punani install tor

test -w "$torrc" || ( error "$torrc is not writable!"; exit 1 ) || exit 1

configure_hidden_service
cat $hidden_service_dir/hostname | send_irc
