#!/bin/sh
make image PROFILE=TLWR703 PACKAGES="tinc curl kmod-ipv6  ip wireless-tools block-mount kmod-usb-core kmod-usb2 kmod-fs-ext4 kmod-usb-storage -kmod-ppp -kmod-pppoe -kmod-pppox -ppp -ppp-mod-pppoe -radvd -dnsmasq" FILES=customfiles/
