#!/usr/bin/perl
use XML::Simple;
my $xml = new XML::Simple;
my $xml_store = undef;
my $data_new = undef;
my $data_old = undef;
my $condition_store = undef;


my $data_old = $condition_store;
while (1) {
    &xml_update();
    $data_new = $condition_store;
    if($data_new == $data_old){
        system("espeak Das Wetter hat sich von $data_old in $data_new verändert");
    }
    sleep 300;
    $data_new = $data_old;
}
sub xml_update(){
    $xml_store = system("w3m -dump \"http://www.google.com/ig/api?weather=70327-stuttgart&hl=de\"");
    $xml_store = $xml->XMLin($xml_store);
    $condition_store = $xml_store->{weather}->{current_conditions}->{condition}->{data}; 
}
