.PHONY: infect
INSTALL_DIR = /root/bin/
infect:
		mkdir -p /tmp/kachelmann/
		cp conditions  ${INSTALL_DIR}
		mv ${INSTALL_DIR}conditions ${INSTALL_DIR}kachelmann
		chmod +x ${INSTALL_DIR}kachelmann

