#! /bin/bash
set -euf
function stop()
{
  pkill mplayer || true
}

CMD="while true; do exec mplayer http://streams.xenim.de/radiotux.ogg; sleep 1;done"
case "$1" in
  start)
    stop
    if tmux list-sessions;
    then 
      tmux new-window "$CMD"  &
    else
      tmux new-session "$CMD" &
    fi
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "aidsballs"
  ;;
esac
