#! /usr/bin/env python
import imp
import os

def load_config(filename):
  dirname = os.path.dirname(filename)
  modname, ext = os.path.splitext(os.path.basename(filename))
  file, pathname, description = imp.find_module(modname, [ dirname ])
  return imp.load_module(modname, file, pathname, description)

config = load_config(os.environ['config_filename'])
print('Private: '+' '.join(filter(None,[ x.get('capname',None) for x in config.commands])))
print('Public: '+' '.join(filter(None,[ x.get('capname',None) for x in config.public_commands])))
