.TH JSONBOT 1 "7 Nov 2010" "Debian GNU/Linux" "jsb manual"
.SH NAME
.B jsb-upload \- The JSONBOT upload program
.SH SYNOPSIS
JSONBOT is a remote event-driven framework for building bots that talk JSON
to each other over XMPP. 
.B jsb-upload 
uploads a release directory to the Google Application Engine (GAE)
.B 
.SH "DESCRIPTION"
.P
With this program you can upload a directory created by the
.B jsb-release
program to the GAE.
.PP
.SH USAGE
.P
.B Usage: jsb-upload [options] <appid>

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -d DATADIR, --datadir=DATADIR
                        datadir to use

.SH "DOCUMENTATION"
See http://jsonbot.org or http://jsonbot.appspot.com/docs for more documentation

.SH "SEE ALSO"
jsb-release(1), jsb-uploadall(1) 

.SH AUTHOR
This manual page was written by Bart Thate <bthate@gmail.com>,
for the Debian GNU/Linux system (but may be used by others).
