.TH JSONBOT 1 "7 Nov 2010" "Debian GNU/Linux" "jsb manual"
.SH NAME
.B jsb-sed \- The JSONBOT sed program
.SH SYNOPSIS
JSONBOT is a remote event-driven framework for building bots that talk JSON
to each other over XMPP. 
.B jsb-sed
is used to sed all files in a directory with provided sedstring.  
.B 
.SH "DESCRIPTION"
.P
This program allows for sedding of whole directories, used when refactoring
jsonbot code. Hope its usefull for other purposes as well.
.PP
.SH USAGE
.P
.B Usage: jsb-sed <dir> <sedstring>
.SH "DOCUMENTATION"
See http://jsonbot.org or http://jsonbot.appspot.com/docs for more documentation

.SH "SEE ALSO"
jsonbot(1)

.SH AUTHOR
This manual page was written by Bart Thate <bthate@gmail.com>,
for the Debian GNU/Linux system (but may be used by others).
