#!/usr/bin/python

from os import environ
from SOAPpy import WSDL
from json import dumps, JSONEncoder

def default(o):
   try:
       iterable = iter(o)
   except TypeError:
       pass
   else:
       return list(iterable)
   return JSONEncoder.default(o)

soap = WSDL.Proxy('https://www.ovh.com/soapi/soapi-re-1.24.wsdl')

username = environ['KREBS_OVH_USER']
password = environ['KREBS_OVH_PASS']

session = soap.login(username, password, 'de', 0)

result = soap.domainList(session)
print dumps(result, sort_keys=True, indent=2, default=default)

soap.logout(session)
