#!/usr/bin/python

from os import environ
from SOAPpy import WSDL

soap = WSDL.Proxy('https://www.ovh.com/soapi/soapi-re-1.24.wsdl')

username = environ['KREBS_OVH_USER']
password = environ['KREBS_OVH_PASS']
domain = argv[2]
subdomain = argv[3]
fieldtype = argv[4]
target = argv[5]

#login
session = soap.login(username, password, 'de', 0)
print "login successfull"

#zoneEntryDel
soap.zoneEntryDel(session, domain, subdomain, fieldtype, target)
print "zoneEntryDel successfull"

#logout
soap.logout(session)
print "logout successfull"
