" not so original .vimrc 
" 2011-11-29
"
" Vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/vundle
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'SudoEdit.vim'
Bundle 'snipMate'
Bundle 'tpope/vim-fugitive'
Bundle 'pyflakes'

filetype plugin indent on

"
set vb
let g:snips_author = 'Bob Ross <root@syntax-fehler.de>'
let g:makefu_author = 'makefu'

""" just for tex

let g:compiler_gcc_ignore_unmatched_lines=1 " ignore for gcc and SCONS
" compiler gcc
set foldenable
set foldmethod=syntax
" shows matching braches etc
set showmatch
set matchtime=3
" highlight search
set hlsearch

let g:load_doxygen_syntax=1

" we do not want any filename~ files    
" set noswapfile
" set nobackup
set backupdir=~/.vim/backup
set directory=~/.vim/backup

" turn off F1
"
inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

" save on focus lost
au FocusLost * :wa

"let TlistAddFilesRecursive = /home/makefu/repos/P2P_MDS " *.cpp *.hpp
let Tlist_Exit_OnlyWindow =1 " exit if other window is closed
nnoremap <silent> <F8> :TlistToggle<CR>
set spelllang=en
" use set spell to enable spelling

" press ttt to rot16 the whole file
nmap ttt ggg?G

colorscheme darkblue
set background=dark

set number
set mouse=
set textwidth=9001
set ignorecase 
set incsearch
set wildignore=*.o,*.obj,*.bak,*.exe,*.os
set shiftwidth=2

syntax on
"For tabstop = 2 spaces
    
set tabstop=2
set et
set sw=2
set smarttab
set autoindent
" end tabstop


set backspace=indent,eol,start
set nocp


" python stuff
" run python code with f5
"autocmd FileType python map <F5> :w<CR>:!python "%"<CR>
" pydiction
"let g:pydiction_location = '~/.vim/plugin/pydiction/complete-dict'

" automatically open and close the popup menu / preview window
au CursorMovedI,InsertLeave * if pumvisible() == 0|silent! pclose|endif
set completeopt=menuone,menu,longest,preview

" somewhere before nowrap is set
set wrap

autocmd BufRead *.json set filetype=json
autocmd FileType json set equalprg=json_reformat
autocmd FileType json set makeprg=jsonval\ %
autocmd FileType json set errorformat=%E%f:\ %m\ at\ line\ %l,%-G%.%#

au  BufNewFile,BufRead *.mustache set syntax=mustache
