#!/bin/sh
#!/bin/bash
 
# domainavailable
# Fast, domain name checker to use from the shell
# Use globs for real fun:
# domainavailable blah{1..3}.{com,net,org,co.uk}
# Inspired by foca / giles:
# http://gilesbowkett.blogspot.com/2009/02/simple-bash-domain-availability.html
 
for d in $@;
do
if host "$d" | grep "NXDOMAIN" >&/dev/null; then
    w=$(whois "$d")
    if ! test "$?" -eq 0 ;then
        echo "$d - whois not available"
    elif echo "$w" | grep -Ei "(No match|NOT FOUND|Status: free)" >&/dev/null; then
        echo "$d available";
    elif echo "$w"| grep -Ei "(Status: invalid)" >&/dev/null ;then
        echo "$d invalid"
    else
        echo "$d taken";
    fi
else
    echo "$d taken";
fi
done
exit 0
