#!/bin/sh
#wrapper for WhatWeb
here=$(dirname `readlink -f $0`)
whatweb_bin="$here/../repos/whatweb/whatweb"
[ -e "$whatweb_bin" ] || ( echo "!! Whatweb app does not exist" && exit 1 )
[ "balls$1" = "balls" ] && ( echo "!! no host given" && exit 1)
exec $whatweb_bin -a 3 "$1"
