#!/bin/sh

make image PROFILE=TLWR703 PACKAGES="wireless-tools kmod-usb-core kmod-usb2 mjpg-streamer usbip usbip-server kmod-video-uvc -radvd -kmod-ppp -kmod-pppoe -kmod-pppox -ppp -ppp-mod-pppoe -dnsmasq" FILES=customfiles/
