.PHONY: infect
install:
		# punani -Ei w3m php php-xml-simple
		ln -s $$PWD/conditions  ../bin/conditions
		ln -s $$PWD/wetter ../bin/wetter
		ln -s ${INSTALL_DIR}conditions ${INSTALL_DIR}kachelmann

