#!/bin/sh
# on MANY WPS-enabled devices the pin is 12345670 , so we can give it a shot
# http://www.wotan.cc/?p=75
cd $(dirname $(readlink -f $0))
. ../lib/wps
. ../lib/plugin_core

parse_plugin_args "$@"
check_painmode
DEFAULT_PIN="${DEFAULT_PIN:-12345670}"

if has_wps "$ENC"; then
    echo "trying PIN $DEFAULT_PIN against $ESSID" >&2
    try_wps_pin "$@" $DEFAULT_PIN
else
    echo "Network $ESSID not WPS enabled" >&2
    exit 1
fi
