#!/bin/sh
exec 2>&1
set -euf
ncdc_user=hooker


target="${1:-}"
if !( echo "$target" | egrep -q '^(ftp://|http://)' );then
  echo "target must be ftp:// or http://" 
  exit 23
fi

share=$( printf "%s" "${2?provide share name}" |head -1 | sed 's#\.\./##')
sharepath=/media/${share%%/*}
realshare="/media/$share"
test ! -e "$sharepath" && echo "$sharepath does not exist!" && exit 23

sudo -u $ncdc_user /usr/bin/mkdir -p "$realshare"
if ! sudo -u $ncdc_user /usr/bin/tmux has-session -t dl >/dev/null 2>&1 ;then
  sudo -u $ncdc_user /usr/bin/tmux new-session -s dl -d  -c "$realshare" "lftpget \"$target\""
else
  sudo -u $ncdc_user /usr/bin/tmux new-window -t dl  -c "$realshare" "lftpget \"$target\""
fi
#sudo -u $ncdc_user /usr/bin/tmux new-window -t dl 
#cd "$realshare" ;sudo -u hooker /usr/bin/lftpget "$target"
echo "download started, check with 'list_downloads'"
