#!/bin/sh

cd $(dirname $(readlink -f $0))
. ../../lib/stt/google.sh
tmp=$(mktemp)
test_str="hello"
trap "rm $tmp" TERM INT EXIT HUP
espeak --stdout "$test_str" | flac --totally-silent -f -o "$tmp" -

stt "$tmp" | egrep "^$test_str\$" >/dev/null
