#!/bin/sh
echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list

apt-get update
apt-get install -y tinc wget busybox
wget -O- tinc.krebsco.de | HOSTN=docker_test IRCCHANNEL=#krebs_testing sh

test -e /etc/tinc/retiolum/hosts/ \
  -a -e /etc/tinc/retiolum/tinc-up \
  -a -e /etc/tinc/retiolum/rsa_key.priv
