#!/bin/sh
set -euf
DB="assets.json"
TMP=`mktemp`

echo "** checking $DB for sanity"
cat $DB | python -m json.tool > $TMP
RET=$?
if [ "$RET" = "0" ];
then
  echo "** Database sanity verified"
  git add $DB
  #mv $TMP $DB
else
  echo "!! Database insane"
  cat $TMP
fi
rm $TMP
exit $RET
