#!/usr/bin/env python
import imp
import os,sys

def load_config(filename):
  dirname = os.path.dirname(filename)
  modname, ext = os.path.splitext(os.path.basename(filename))
  file, pathname, description = imp.find_module(modname, [ dirname ])
  return imp.load_module(modname, file, pathname, description)

config = load_config(os.environ['config_filename'])

with open(config.admin_file) as f:
  for line in f:
    nick,secret = line.split()
    if sys.argv[1] == secret:
      print("identified you as %s!"%nick)
      with open(config.auth_file,'a+') as g:
        g.write(os.environ['_prefix'] +"\n")
      sys.exit(0)

print("unable to identify you, sorry")
