#!/usr/bin/env python3
import json
from os import environ
import sys
import os
# krebs polling
import poll

f = 'suggestions.json'
title=" ".join(sys.argv[1:])
db = poll.save_db(f,[])
print("cleared database")
