#!/bin/sh

cd $(dirname $(readlink -f $0))
if [ ! -e Makefile ] ;then 
    echo "ImageBuilder not checked out yet"
    echo "try running ../prepare $$PROFILE"
    exit 1
fi

echo 
if [ -e ./custom_make ];then
    echo "Starting Custom Make"
    sh ./custom_make 2>/dev/null | while read line; do
        echo -n .
    done
else
    echo "No Custom Make Script exists, bailing out!"
    exit 1
fi

echo
cat << EOF
finished building 
You can use the following images:
    Factory       : $PWD/bin/ar71xx/openwrt-ar71xx-generic-tl-wr703n-v1-squashfs-factory.bin
    System Upgrade: $PWD/bin/ar71xx/openwrt-ar71xx-generic-tl-wr703n-v1-squashfs-sysupgrade.bin
EOF
