#! /bin/bash
set -euf
CMD="mplayer http://somafm.com/groovesalad.pls"
function start() {
  stop
  tmux list-sessions &&
      tmux new-window "$CMD" ||
      tmux new-session "$CMD" ||
}
function stop()
{
  pkill mplayer || :
}

case "$1" in
  start)
    start
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "aidsballs"
  ;;
esac
