#!/bin/sh
set -euf
IMAGEBUILDER_URL="http://downloads.openwrt.org/attitude_adjustment/12.09-beta2/ar71xx/generic/OpenWrt-ImageBuilder-ar71xx_generic-for-linux-i486.tar.bz2"

cd $(dirname $(readlink -f $0))
if [ x"${1:-}" == x ];then
    echo "usage: $0 PROFILE"
    echo
    echo "Available Profiles:"
    ls -1 profiles/ |grep -v '^README' | grep -v '^init$' | while read profile; do
        echo "    $profile"
    done
    exit 1
fi
PROFILE=$1
if [ ! -e builder/Makefile ]; then
    wget -O- $IMAGEBUILDER_URL | tar xj OpenWrt-ImageBuilder-ar71xx_generic-for-linux-i486
    mv -f OpenWrt-ImageBuilder-ar71xx_generic-for-linux-i486 builder
    echo "Builder successfully downloaded"
else
    echo "Builder already installed, skipping download"
fi
echo
echo "copying generic init:"
cp --remove-destination  profiles/init  builder/init
echo "  profile/init -> builder/init"
[ -e builder/overlay ] && echo "removing old overlay" && rm -rf builder/overlay
echo
echo "copying profile:"
find  profiles/$PROFILE -mindepth 1 -maxdepth 1| while read file; do
    echo "  $file -> builder/$(basename $file)"
    rm -rf builder/$(basename $file)
    cp -r $file builder/
done

echo
echo $PROFILE > builder/current_profile
echo "Finished Preparing Profile $PROFILE"
echo 'run `builder/init`'

if [ -e builder/overlay ];then
    echo
    echo "This profile also contains overlay data,"
    echo 'run `builder/init_overlay` to copy'
fi
