#!/usr/bin/python

import pynotify,os,sys

imageURI = os.path.abspath(os.path.normpath(os.path.dirname(sys.argv[0]) + '/../../../bling/krebs_plain_negate_nobg.png'))
try:
  TITLE=os.environ.get('method','clive') + ':' + os.environ.get('id','-1')
  MESSAGE=os.environ.get('params','No Message')
except:
  print("Error 1: You are made of stupid!")
  exit(23)

pynotify.init("Notif App",)
print imageURI
n = pynotify.Notification(TITLE, MESSAGE,imageURI)
n.set_timeout(20000)
n.show()
