#! /bin/sh
#
# cnot - cholerab live command line notification client, bitch!
#
# usage: cnot hostname message...
#
set -euf

host="$1"; shift
port=42101

params="$*"

exec curl -vsS -X PUT --data-binary @- "http://$host:$port" <<EOF
{"method":"clive","params":"$params","id":null}
EOF
