#custom stuff
export PATH=$PATH:/krebs/bin:$HOME/bin

# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set to the name theme to load.
# Look in ~/.oh-my-zsh/themes/
export ZSH_THEME="gallifrey"
#export ZSH_THEME="fishy"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git ssh-agent)
source $ZSH/oh-my-zsh.sh
source ~/.bash_alias
# Customize to your needs...
HISTFILE=~/.histfile
HISTSIZE=900000
SAVEHIST=900000
#PS1='[%n@%m %~]$ '
export EDITOR=vim
#export JAVA_HOME=/usr/lib/jvm/java-6-openjdk
export JAVA_HOME=/opt/java/jre
GREP_COLOR="1;33"
alias ls='ls --color=auto'
alias grep='grep --color=auto'

export MANPATH=$MANPATH:/home/makefu/man

if [ -f "$HOME/.dircolors" ] ; then
  eval `dircolors -b "$HOME/.dircolors"`
  export LS_COLORS
fi

# node.js
export PATH=$HOME/local/node/bin:$PATH

fortune -a
echo "--"
#test -r ~/EVENTS && cat ~/EVENTS
task
echo "--"
#test -r ~/TODO  && cat ~/TODO 

test -r ~/Dropbox/shared_shell && source ~/Dropbox/shared_shell
setopt menu_complete
unsetopt correct_all
export PATH=$PATH:/home/makefu/CodeSourcery/Sourcery_G++_Lite/bin
