
# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Look in ~/.oh-my-zsh/themes/
export ZSH_THEME="gallifrey"

# Comment this out to disable weekly auto-update checks
export DISABLE_AUTO_UPDATE="true"

# export DISABLE_LS_COLORS="true"

plugins=(git ssh-agent)
source $ZSH/oh-my-zsh.sh
test -e $HOME/.bash_alias && source $HOME/.bash_alias

# Customize to your needs...
export PATH=$PATH:/krebs/bin:$HOME/bin
HISTFILE=~/.histfile
HISTSIZE=900001
SAVEHIST=900001

export EDITOR=vim

export JAVA_HOME=/opt/java/jre

GREP_COLOR="1;33"
alias grep='grep --color=auto'

export MANPATH=$MANPATH:$HOME/man

if [ -f "$HOME/.dircolors" ] ; then
  eval `dircolors -b "$HOME/.dircolors"`
  export LS_COLORS
fi

which fortune >/dev/null && fortune -a
which task >/dev/null && task
echo "--"
test -r ~/TODO  && cat ~/TODO 

test -r ~/Dropbox/shared_shell && source ~/Dropbox/shared_shell
setopt menu_complete
unsetopt correct_all
