#!/bin/sh
echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
apt-get update
apt-get -y install redis-server nodejs npm
npm config set registry http://registry.npmjs.org/
cd /krebs/go
npm install
PORT=80 node .
