install:
	ln -snf $$PWD/mtgox/ticker_text.sh ../bin/mtgox_ticker
	ln -snf $$PWD/scex/ticker_text.sh ../bin/scex_ticker
	ln -snf $$PWD/mooncoin/ticker_text.sh ../bin/mooncoin_ticker
	ln -snf $$PWD/bitcoinslc/stats_text.sh ../bin/bitcoinslc_stats
