#!/usr/bin/python

from os import environ
from os.path import dirname, realpath
from SOAPpy import WSDL
from json import dumps, JSONEncoder

def default(o):
   try:
       iterable = iter(o)
   except TypeError:
       pass
   else:
       return list(iterable)
   return JSONEncoder.default(o)

wsdl = dirname(realpath(__file__)) + '/soapi.wsdl'
soap = WSDL.Proxy(wsdl)

username = environ['KREBS_OVH_USER']
password = environ['KREBS_OVH_PASS']
domain = environ.get('KREBS_OVH_DOMAIN','krebsco.de')

session = soap.login(username, password, 'de', 0)

result = soap.domainCapabilities(session, domain)
print dumps(result, sort_keys=True, indent=2, default=default)

soap.logout(session)
