#!/usr/bin/python

from os import environ
from os.path import dirname, realpath
from SOAPpy import WSDL
from sys import argv
from json import dumps, JSONEncoder

def default(o):
   try:
       iterable = iter(o)
   except TypeError:
       pass
   else:
       return list(iterable)
   return JSONEncoder.default(o)

wsdl = dirname(realpath(__file__)) + '/soapi-re-1.24.wsdl'
soap = WSDL.Proxy(wsdl)

username = environ['KREBS_OVH_USER']
password = environ['KREBS_OVH_PASS']
domain = argv[1]
subdomain = argv[2] if argv[2] is not " " else ""
fieldtype = argv[3]
target = argv[4]

session = soap.login(username, password, 'de', 0)

result = soap.zoneEntryAdd(session, domain, subdomain, fieldtype, target,1)
print dumps(result, sort_keys=True, indent=2, default=default)

soap.logout(session)
