#!/usr/bin/python2
import simplejson,urllib,datetime
url="http://bitcoinpool.com/pooljson.php"
f = open('/home/makefu/log/bitcoinpool_stats',mode='a')
today = datetime.datetime.now()

result = simplejson.load(urllib.urlopen(url))
print >>f, today.strftime("%Y-%m-%dT%H:%M:%S"),
for k,v in result.iteritems():
    print >>f ,'%s' % v,
print >>f
