#!/bin/sh

make image PROFILE=TLWR703 PACKAGES="wireless-tools block-mount kmod-usb-core kmod-usb2 kmod-usb-storage kmod-fs-ext4 -kmod-ppp -kmod-pppoe -kmod-pppox -ppp -ppp-mod-pppoe -dnsmasq kmod-video-uvc -radvd" FILES=customfiles/
