all:
	mkdir -p /etc/tinc/retiolum
	git clone git://github.com/miefda/retiolum.git /etc/tinc/retiolum/hosts
	echo cd /etc/tinc/retiolum/hosts/.scripts
	echo "choose the right build script from here"
update:
	cd /etc/tinc/retiolum/hosts
	git pull origin master
